# Base configuration for billing service
# This configuration is shared across all environments

# Storage configuration
storage:
  type: "postgres" # memory, postgres

# Database migration configuration
migration:
  enabled: true
  path: "database/migrations"
  auto_migrate: false # Run migrations automatically on startup
  table_name: "schema_migrations"

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  shutdown_timeout: 15s

database:
  host: "localhost"
  port: 5432
  user: "billing_app_dev_user"     # Application user for runtime
  password: "billing_app_dev_2025" # Will be overridden by environment
  dbname: "go-labs-dev"            # Shared application database
  schema: "billing"                # Service-specific schema
  sslmode: "disable"

  # Connection pool settings
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  conn_max_idle_time: "5m"

  # Logging
  log_level: "info" # silent, error, warn, info

logging:
  level: "info"
  format: "json" # json, text
  output: "stdout" # stdout, stderr, file
  file_path: "/var/log/billing-service.log"

api:
  prefix: "/api/v1"
  enable_cors: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  cors_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  cors_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"

# Rate limiting
rate_limit:
  enabled: true
  requests_per_minute: 60
  burst: 10

# Health check
health:
  endpoint: "/health"
  database_check: true

# Metrics
metrics:
  enabled: true
  endpoint: "/metrics"
  namespace: "billing_service"

# Tracing
tracing:
  enabled: false
  service_name: "billing-service"
  jaeger_endpoint: "http://localhost:14268/api/traces"
