# Development environment configuration
# Overrides base.yaml settings for local development

# Use PostgreSQL storage for real database development
storage:
  type: "postgres"

# Enable auto-migration in development for convenience
migration:
  auto_migrate: true

server:
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "billing_app_dev_user"        # Application user for runtime (DML only)
  password: "billing_app_dev_2025"    # Application user password
  dbname: "go-labs-dev"               # Shared application database
  schema: "billing"                   # Service-specific schema
  sslmode: "disable"
  log_level: "info"

# Migration database configuration (for schema changes)
migration_database:
  host: "localhost"
  port: 5432
  user: "billing_migration_dev_user"  # Migration user for DDL operations
  password: "billing_migration_dev_2025" # Migration user password
  dbname: "go-labs-dev"               # Same database, different user
  schema: "billing"                   # Service-specific schema
  sslmode: "disable"

logging:
  level: "debug"
  format: "text"
  output: "stdout"

api:
  enable_cors: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://localhost:8080"

rate_limit:
  enabled: false # Disable for development

# Enable detailed metrics in development
metrics:
  enabled: true

tracing:
  enabled: false # Enable when needed for debugging