# Test environment configuration
# Used specifically for integration tests that require PostgreSQL

# Use PostgreSQL storage for integration tests
storage:
  type: "postgres"

# Enable auto-migration for integration tests
migration:
  enabled: true
  auto_migrate: true

# Test database configuration - shared application database
database:
  host: "localhost"
  port: 5432  # Standard PostgreSQL port - requires local PostgreSQL installation
  user: "billing_app_tst_user"        # Application user for runtime (DML only)
  password: "billing_app_tst_2025"    # Application user password
  dbname: "go-labs-tst"               # Shared application database
  schema: "billing"                   # Service-specific schema
  sslmode: "disable"
  log_level: "error" # Minimal logging during tests

# Migration database configuration (for schema changes)
migration_database:
  host: "localhost"
  port: 5432
  user: "billing_migration_tst_user"  # Migration user for DDL operations
  password: "billing_migration_tst_2025" # Migration user password
  dbname: "go-labs-tst"               # Same database, different user
  schema: "billing"                   # Service-specific schema
  sslmode: "disable"

# Test logging (minimal for clean test output)
logging:
  level: "error"
  format: "text"
  output: "stdout"

# Disable unnecessary features during tests
api:
  enable_cors: false

rate_limit:
  enabled: false

health:
  database_check: false # Skip health checks during tests

metrics:
  enabled: false

tracing:
  enabled: false