name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-response:
    # Only run if the comment contains @claude
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    permissions:
      contents: read          # Read repository code
      pull-requests: write    # Comment on PRs
      issues: write          # Comment on issues
      
    steps:
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Note: ANTHROPIC_API_KEY will be needed for advanced features
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}