name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-response:
    # Only run if the comment contains @claude and is on a PR
    if: contains(github.event.comment.body, '@claude') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    
    permissions:
      contents: read          # Read repository code
      pull-requests: write    # Comment on PRs
      issues: write          # Comment on issues
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout PR branch
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}